### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [EulerianTechnologies/gtm-template-eulerian-analytics#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values that are then used as your url. These methods take in a single text argument and returns an encoded Uniform Resource Identifier (URI) by escaping special characters. They return a string that represents the provided string encoded as a URI. You should use this method on "trackingDomain" when generating the url
const url = 'https://'+ trackingDomain +'/ea.js';

**Comment by matjmat** [comment]
fixed
